<?php
/**
 * SSO hook callbacks and helper functions.
 *
 * @package tutor-sso
 */

namespace TutorSSO;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

// ── Internal option helper ────────────────────────────────────────────────────

/**
 * Retrieve a plugin option by its short key.
 * All plugin options are stored under the 'tutor_sso_' prefix.
 *
 * @param string $key     Option key without the 'tutor_sso_' prefix.
 * @param mixed  $default Default value when the option is empty.
 * @return mixed
 */
function sso_option( $key, $default = '' ) {
	return get_option( 'tutor_sso_' . $key, $default );
}

// ── 1. OAuth 2.0 callback handler ────────────────────────────────────────────

/**
 * Handle the authorization-code callback from the LMS.
 *
 * Runs on every 'init', but returns immediately when the 'code' query
 * parameter is absent so normal page loads are unaffected.
 *
 * FIXES vs original:
 * - Removed unused `use Edly\Utils` import.
 * - Sanitize and unslash $_GET values before use.
 * - Added CSRF protection via a state parameter / transient (OAuth best
 *   practice; the original had no state check at all).
 * - Added null-check for required user fields (preferred_username, email)
 *   before touching the database.
 * - Handle WP_Error returned by create_or_update_user().
 * - Post-login redirect uses wp_safe_redirect() with the configured host
 *   whitelisted, replacing a plain wp_safe_redirect() that could silently
 *   fall back to the home URL for external destinations.
 */
function validate_sso_login() {

	// ── LMS-side OAuth error (no code, but error param present) ─────────────
	if ( isset( $_GET['error'] ) ) { // phpcs:ignore WordPress.Security.NonceVerification
		$error             = sanitize_text_field( wp_unslash( $_GET['error'] ) ); // phpcs:ignore WordPress.Security.NonceVerification
		$error_description = isset( $_GET['error_description'] ) // phpcs:ignore WordPress.Security.NonceVerification
			? sanitize_text_field( wp_unslash( $_GET['error_description'] ) ) // phpcs:ignore WordPress.Security.NonceVerification
			: '';
		error_log( sprintf( '[tutor-sso] LMS OAuth error: %s — %s', $error, $error_description ) );
		wp_safe_redirect( get_site_url() );
		exit;
	}

	if ( empty( $_GET['code'] ) ) { // phpcs:ignore WordPress.Security.NonceVerification
		return;
	}

	// ── CSRF: verify the state parameter ─────────────────────────────────────
	// The state was generated by get_lms_login_url() and stored as a transient.
	$state = isset( $_GET['state'] ) // phpcs:ignore WordPress.Security.NonceVerification
		? sanitize_text_field( wp_unslash( $_GET['state'] ) ) // phpcs:ignore WordPress.Security.NonceVerification
		: '';

	if ( empty( $state ) || ! get_transient( 'tutor_sso_state_' . $state ) ) {
		error_log( '[tutor-sso] State validation failed — state param missing or transient not found.' );
		wp_safe_redirect( get_site_url() );
		exit;
	}

	// One-time use: delete immediately after the check.
	delete_transient( 'tutor_sso_state_' . $state );

	// ── Exchange the code for tokens ──────────────────────────────────────────
	$code    = sanitize_text_field( wp_unslash( $_GET['code'] ) ); // phpcs:ignore WordPress.Security.NonceVerification
	$handler = new OAuth_Handler();

	$token_data = $handler->get_id_token(
		sso_option( 'access_token_url' ),
		'authorization_code',
		sso_option( 'client_id' ),
		sso_option( 'client_secret' ),
		$code,
		sso_option( 'redirect_url' )
	);

	$id_token = $token_data['id_token'] ?? $token_data['access_token'] ?? '';

	if ( empty( $id_token ) ) {
		wp_die( esc_html__( 'Invalid token received. Please contact the site administrator.', 'tutor-sso' ) );
	}

	// ── Decode the JWT payload and validate required fields ───────────────────
	$user_data = $handler->get_user_data_from_id_token( $id_token );

	if ( empty( $user_data['preferred_username'] ) || empty( $user_data['email'] ) ) {
		wp_die(
			esc_html__( 'Required fields (preferred_username, email) are missing from the token payload. Please contact the site administrator.', 'tutor-sso' )
		);
	}

	// ── Create / update the WordPress user ───────────────────────────────────
	$blog_id  = get_current_blog_id();
	$username = $user_data['preferred_username'];
	$email    = sanitize_email( $user_data['email'] );

	$user_id = create_or_update_user( $username, $email, 'subscriber', $blog_id );

	if ( is_wp_error( $user_id ) ) {
		wp_die(
			esc_html__( 'Could not create or retrieve your WordPress account. Please contact the site administrator.', 'tutor-sso' )
		);
	}

	$user = get_user_by( 'id', $user_id );

	link_user_to_blog( $user_id, $blog_id );
	wp_set_current_user( $user_id );
	wp_set_auth_cookie( $user_id );
	do_action( 'wp_login', $user->user_login, $user );

	// ── Redirect after login ──────────────────────────────────────────────────
	$redirect_url = sso_option( 'signin_redirect_url' ) ?: get_site_url( $blog_id );

	// wp_safe_redirect() only permits same-host URLs by default.
	// Allow whatever host the admin has configured.
	add_filter(
		'allowed_redirect_hosts',
		function ( $hosts ) use ( $redirect_url ) {
			$host = wp_parse_url( $redirect_url, PHP_URL_HOST );
			if ( $host ) {
				$hosts[] = $host;
			}
			return $hosts;
		}
	);

	// Clear the cached email-verification state so the first page after a fresh
	// login re-checks the API (handles account switches and newly verified emails).
	setcookie( 'edxemailverified', '', time() - DAY_IN_SECONDS, '/', '', is_ssl(), false );

	wp_safe_redirect( $redirect_url );
	exit;
}
add_action( 'init', __NAMESPACE__ . '\\validate_sso_login' );

// ── 2. Build the LMS authorization URL ───────────────────────────────────────

/**
 * Build the OAuth 2.0 authorization URL that starts the SSO login flow.
 *
 * A fresh, cryptographically random state token is generated on every call
 * and stored as a transient (10-minute TTL). Because the state is ephemeral,
 * do NOT cache pages that render this URL.
 *
 * @return string Full authorization URL including client_id, redirect_uri,
 *                response_type, and state parameters.
 */
function get_lms_login_url() {

	// Generate a random, URL-safe state token for CSRF protection.
	$state = wp_generate_password( 32, false );
	set_transient( 'tutor_sso_state_' . $state, true, 10 * MINUTE_IN_SECONDS );

	return add_query_arg(
		array(
			'client_id'     => sso_option( 'client_id' ),
			'redirect_uri'  => sso_option( 'redirect_url' ),
			'response_type' => 'code',
			'state'         => $state,
		),
		sso_option( 'authorize_endpoint' )
	);
}

// ── 3. Redirect to the LMS logout page on WordPress logout ───────────────────

/**
 * When a user logs out of WordPress, also send them to the LMS logout
 * endpoint so both sessions are terminated together.
 *
 * FIX vs original: The original used wp_redirect() (no host validation).
 * Now uses wp_safe_redirect() with the LMS host added to the whitelist.
 */
function redirect_to_lms_logout() {

	$lms_base = rtrim( sso_option( 'lms_base_url' ), '/' );

	if ( empty( $lms_base ) ) {
		return;
	}

	add_filter(
		'allowed_redirect_hosts',
		function ( $hosts ) use ( $lms_base ) {
			$host = wp_parse_url( $lms_base, PHP_URL_HOST );
			if ( $host ) {
				$hosts[] = $host;
			}
			return $hosts;
		}
	);

	wp_safe_redirect( $lms_base . '/logout' );
	exit;
}
add_action( 'wp_logout', __NAMESPACE__ . '\\redirect_to_lms_logout' );

// ── 4. Hide the admin bar for non-admin roles ─────────────────────────────────

/**
 * Return true only when the current user has an admin-level role, so the
 * admin bar is hidden from regular subscribers.
 *
 * @return bool
 */
function show_admin_bar_for_admins_only() {
	$user          = wp_get_current_user();
	$allowed_roles = array( 'administrator', 'edly_admin' );
	return (bool) array_intersect( $allowed_roles, (array) $user->roles );
}
add_filter( 'show_admin_bar', __NAMESPACE__ . '\\show_admin_bar_for_admins_only' );

// ── 5. Block wp-admin for non-admin users ─────────────────────────────────────

/**
 * Redirect non-admin users away from the WordPress dashboard.
 * AJAX requests are always allowed through.
 */
function block_dashboard_for_non_admins() {

	$user          = wp_get_current_user();
	$allowed_roles = array( 'administrator', 'edly_admin' );
	$is_ajax       = defined( 'DOING_AJAX' ) && DOING_AJAX;

	if (
		! empty( $user->roles )
		&& ! array_intersect( $allowed_roles, $user->roles )
		&& is_admin()
		&& ! $is_ajax
	) {
		wp_safe_redirect( home_url() );
		exit;
	}
}
add_action( 'init', __NAMESPACE__ . '\\block_dashboard_for_non_admins' );

// ── 6. Auto-logout when the LMS session cookie disappears ────────────────────

/**
 * Destroy the WordPress session when the user's Open edX session cookies are
 * absent, keeping the two sessions in sync without requiring an explicit
 * WordPress logout.
 *
 * Relies on the standard Open edX / Tutor cookie names:
 *   - edxloggedin   (boolean flag cookie)
 *   - edx-user-info (JSON user-info cookie)
 *
 * If your Tutor deployment uses a custom PLATFORM_NAME, the cookie names may
 * differ (they follow the pattern {platform_name}loggedin). Adjust as needed.
 *
 * NOTE: super-admins are never auto-logged-out so maintenance work is not
 * interrupted by a missing LMS session.
 */
function revoke_session_on_lms_logout() {

	if ( ! wp_validate_auth_cookie( '', 'logged_in' ) ) {
		return;
	}

	if ( current_user_can( 'manage_options' ) ) {
		return;
	}

	$has_edx_logged_in = ! empty( $_COOKIE['edxloggedin'] );
	$has_edx_user_info = isset( $_COOKIE['edx-user-info'] );

	if ( ! $has_edx_logged_in || ! $has_edx_user_info ) {
		wp_destroy_current_session();
		wp_clear_auth_cookie();
		wp_set_current_user( 0 );
	}
}
add_action( 'init', __NAMESPACE__ . '\\revoke_session_on_lms_logout', 25 );

// ── 7. User creation / update ─────────────────────────────────────────────────

/**
 * Create a new WordPress user or synchronise an existing one, then make sure
 * they belong to the current blog (multisite only).
 *
 * FIXES vs original:
 * - Uses wp_update_user( array() ) instead of mutating $user directly, which
 *   was not being persisted to the database correctly.
 * - Guards add_user_to_blog() behind is_multisite() — the function is a no-op
 *   on single-site installs but calling it adds unnecessary overhead.
 * - Returns a proper WP_Error on failure instead of a bare `new \WP_Error()`.
 *
 * @param string $username User login name.
 * @param string $email    User e-mail address (already sanitized).
 * @param string $role     WordPress role to assign on first creation.
 * @param int    $blog_id  Target blog/site ID.
 * @return int|\WP_Error   User ID on success, WP_Error on failure.
 */
function create_or_update_user( $username, $email, $role, $blog_id ) {

	$user = get_user_by( 'login', $username );

	if ( ! $user ) {
		$user_id = wpmu_create_user( $username, wp_generate_password(), $email );

		if ( ! $user_id ) {
			return new \WP_Error(
				'tutor_sso_user_creation_failed',
				__( 'Failed to create the WordPress user account.', 'tutor-sso' )
			);
		}

		if ( is_multisite() ) {
			add_user_to_blog( $blog_id, $user_id, $role );
		}
	} else {
		$user_id = $user->ID;

		// Keep the e-mail address in sync with the LMS.
		if ( $email !== $user->user_email ) {
			wp_update_user(
				array(
					'ID'         => $user_id,
					'user_email' => $email,
				)
			);
		}
	}

	return $user_id;
}

// ── 8. Blog membership helper ─────────────────────────────────────────────────

/**
 * Add a user to a blog if they are not already a member (multisite only).
 *
 * @param int    $user_id User ID.
 * @param int    $blog_id Blog/site ID.
 * @param string $role    Role to assign when adding for the first time.
 */
function link_user_to_blog( $user_id, $blog_id, $role = 'subscriber' ) {
	if ( is_multisite() && ! is_user_member_of_blog( $user_id, $blog_id ) ) {
		add_user_to_blog( $blog_id, $user_id, $role );
	}
}

// ── 9. Suppress the heartbeat auth-check modal ───────────────────────────────

// Prevent the "You have been logged out" popup on the front end.
// SSO users should be handled by revoke_session_on_lms_logout() above.
add_filter( 'wp_auth_check_load', '__return_false' );

// ── 10. Login / logout button shortcode ──────────────────────────────────────

/**
 * Render a login button for logged-out visitors and a logout button for
 * logged-in users from a single shortcode.
 *
 * Attributes:
 *   label        - Text for the login button   (default "Log in with LMS").
 *   logout_label - Text for the logout button  (default "Log out").
 *
 * Backward compatible: [tutor_sso_login label="…"] still works exactly as
 * before for logged-out visitors; logged-in users now see a logout button
 * instead of nothing.
 */
add_shortcode( 'tutor_sso_login', function ( $atts ) {

    $atts = shortcode_atts(
        [
            'label'        => __( 'Log in with LMS', 'tutor-sso' ),
            'logout_label' => __( 'Log out', 'tutor-sso' ),
        ],
        $atts,
        'tutor_sso_login'
    );

    if ( is_user_logged_in() ) {
        return sprintf(
            '<a href="%s" class="tutor-sso-logout-btn">%s</a>',
            esc_url( wp_logout_url() ),
            esc_html( $atts['logout_label'] )
        );
    }

    $url = \TutorSSO\get_lms_login_url();

    return sprintf(
        '<a href="%s" class="tutor-sso-login-btn">%s</a>',
        esc_url( $url ),
        esc_html( $atts['label'] )
    );
} );

// ── 11. Start-learning button shortcode ───────────────────────────────────────

/**
 * Render a "Start learning" button that links to the LMS dashboard.
 *
 * Attributes:
 *   label - Button text. Default "Start learning".
 *   url   - Destination URL. Defaults to the configured course dashboard URL
 *           (tutor_sso_course_dashboard_url), then the LMS base URL, with
 *           /learner-dashboard/ appended.
 *
 * Only rendered for logged-in users.
 *
 * Example: [tutor_sso_start_learning label="ابدأ التعلم" url="https://lms.example.com/dashboard"]
 */
add_shortcode( 'tutor_sso_start_learning', function ( $atts ) {

    if ( ! is_user_logged_in() ) {
        return '';
    }

    $atts = shortcode_atts(
        [
            'label' => __( 'Start learning', 'tutor-sso' ),
            'url'   => '',
        ],
        $atts,
        'tutor_sso_start_learning'
    );

    $url = $atts['url'];

    if ( empty( $url ) ) {
        $base = sso_option( 'course_dashboard_url' ) ?: sso_option( 'lms_base_url' );
        $base = rtrim( (string) $base, '/' );
        $url  = $base ? $base . '/learner-dashboard/' : '';
    }

    if ( empty( $url ) ) {
        return '';
    }

    return sprintf(
        '<a href="%s" class="tutor-sso-start-learning-btn">%s</a>',
        esc_url( $url ),
        esc_html( $atts['label'] )
    );
} );